// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7-nN6KuCCpv7xt6weeO_7M_1w-E3gVHk',
    appId: '1:259940867885:web:681712d5346f7d37573da4',
    messagingSenderId: '259940867885',
    projectId: 'dictionary-flutter-v0',
    authDomain: 'dictionary-flutter-v0.firebaseapp.com',
    storageBucket: 'dictionary-flutter-v0.appspot.com',
    measurementId: 'G-MSWP00169S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGniCMxMZvdzk17T3uoJSvetlkfQ9b1Dw',
    appId: '1:259940867885:android:81a82ef22dac0efd573da4',
    messagingSenderId: '259940867885',
    projectId: 'dictionary-flutter-v0',
    storageBucket: 'dictionary-flutter-v0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk4kMCIKsBeoTdgQFbIZXC2OGamvchxa0',
    appId: '1:259940867885:ios:cd3bce9c292265f2573da4',
    messagingSenderId: '259940867885',
    projectId: 'dictionary-flutter-v0',
    storageBucket: 'dictionary-flutter-v0.appspot.com',
    iosBundleId: 'com.example.vocabify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk4kMCIKsBeoTdgQFbIZXC2OGamvchxa0',
    appId: '1:259940867885:ios:cd3bce9c292265f2573da4',
    messagingSenderId: '259940867885',
    projectId: 'dictionary-flutter-v0',
    storageBucket: 'dictionary-flutter-v0.appspot.com',
    iosBundleId: 'com.example.vocabify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7-nN6KuCCpv7xt6weeO_7M_1w-E3gVHk',
    appId: '1:259940867885:web:676c0e2da0d77241573da4',
    messagingSenderId: '259940867885',
    projectId: 'dictionary-flutter-v0',
    authDomain: 'dictionary-flutter-v0.firebaseapp.com',
    storageBucket: 'dictionary-flutter-v0.appspot.com',
    measurementId: 'G-YX1Y80XQK8',
  );

}